version: '3.8'

services:
  redis:
    image: redis:7.2.4
    volumes:
      - redis-data:/data
  dash:
    depends_on:
      - init-db
      - redis
    build:
      context: ./dashpress
      dockerfile: Dockerfile
    env_file: dashpress/.env
    ports:
      - "3000:80"
    volumes:
      - app-data:/app
    labels:
      - "hobby-hoster.enable=true"
  db:
    image: postgres:16.2
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  init-db:
    depends_on:
      - db
    build:
      context: ./postgres
      dockerfile: Dockerfile
volumes:
  redis-data:
  db-data:
  app-data:
